### ISSUE TITLE
[FEATURE] Upgrade script from github if a newer version is available

### ISSUE THREAD

**Issue by 0xFTW** [thecyberworld/docser#3]
### Detailed description

The project should check if there is a new commit on github and if there is one the it should upgrade the tool with all the new changes available.

### Context

A user can simple run `docser --upgrade` and then project should check if there is a new commit on github and if there is one the it should upgrade the tool with all the new changes available.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sculley** [comment]
Hello @0xFTW I would like to work on this issue to add the ability to upgrade `docser` from the application itself. Could you assign this to me?

**Comment by 0xFTW** [comment]
Sure! @sculley

**Comment by 0xFTW** [comment]
Hi @sculley, is there any update?

**Comment by sculley** [comment]
@0xFTW - I will send a PR over the weekend.

I currently am working on a solution that relies on the releases in GitHub, it checks if the there is a release which is newer than the binary being ran and if so downloads/extracts and then updates the local binary.

What are you thoughts is that the approach you envisioned?

**Comment by sculley** [comment]
So noticed we don't include the binary in the releases, which doesn't work well with my solution.

I was thinking that ideally this `docser --upgrade` feature could be used from a built binary but can look into downloading latest code and building on the fly too.

**Comment by kabir0x23** [comment]
> So noticed we don't include the binary in the releases, which doesn't work well with my solution.
> 
> I was thinking that ideally this `docser --upgrade` feature could be used from a built binary but can look into downloading latest code and building on the fly too.

we can add binaries, i will add by today

do have any another option, or this one is the most optimal solution?

**Comment by sculley** [comment]
@kabir0x23 - I for see two different solutions

Solution 1 - Download/Replace pre-existing Go Binary
Solution 2 - Download/Build/Replace pre-existing Go Binary

I am currently looking into both and will write code for both and test, I feel like Solution 1 would be cleaner but this would require we update the Github Action release workflow to build binaries for all intended platforms/architectures i.e. Windows/Linux/Darwin & AMD64/ARM64 (potentially many more)

Solution 2 wouldn't require any modifications to the Github Actions release workflow but will require more code (I suspect)

What are your thoughts?

**Comment by sculley** [comment]
@kabir0x23 @0xFTW - I am ready to submit a PR which I have tested inside my fork. There is only a tagged release in the releases but we need an actual release as my code relies on the Github API to obtain the latest release (this can't be done with tags)

https://github.com/thecyberworld/docser/releases

I have chosen to build the binary rather than downloading pre-existing binaries as that requires further work to the Github Actions.

Can you please add a v0.1.0 release today to the releases page? as soon as that is ready I can submit my PR.

**Comment by kabir0x23** [comment]
> @kabir0x23 @0xFTW - I am ready to submit a PR which I have tested inside my fork. There is only a tagged release in the releases but we need an actual release as my code relies on the Github API to obtain the latest release (this can't be done with tags)
> 
> https://github.com/thecyberworld/docser/releases
> 
> I have chosen to build the binary rather than downloading pre-existing binaries as that requires further work to the Github Actions.
> 
> Can you please add a v0.1.0 release today to the releases page? as soon as that is ready I can submit my PR.

Yes sure, will add by today

Thank you..

**Comment by sculley** [comment]
@kabir0x23 @0xFTW - I have submitted #7 I have written in way so that if it can't find a release in the GitHub release page (which there currently isn't) it will return a message

```
Unable to find the latest release, exiting.
```

Which should allow this PR to be reviewed/approved/merged and then once you have time to add the releases it will work.

The change makes use of constants to track the current version and should be updated for all future releases.

```
const (
	owner          = "thecyberworld"
	repo           = "docser"
	currentVersion = "v0.1.0"
)
```

**Comment by kabir0x23** [comment]
> @kabir0x23 @0xFTW - I have submitted #7 I have written in way so that if it can't find a release in the GitHub release page (which there currently isn't) it will return a message
> 
> ```
> Unable to find the latest release, exiting.
> ```
> 
> Which should allow this PR to be reviewed/approved/merged and then once you have time to add the releases it will work.
> 
> The change makes use of constants to track the current version and should be updated for all future releases.
> 
> ```
> const (
> 	owner          = "thecyberworld"
> 	repo           = "docser"
> 	currentVersion = "v0.1.0"
> )
> ```

Hey @sculley 
thanks for your contributions, we will review it by today
